export class CommonUrls {
  public static readonly WORK_HALL_REVIVE_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/taskcenter/tasktodoNew';
  public static readonly WORK_HALL_PROGRESS_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/myserviceapply/indexNew';
  public static readonly WORK_HALL_SCORE_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#from=formhome&act=fp/myserviceapply/indexFinish';
  public static readonly WORK_HALL_CLOSED_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/myserviceapply/indexFinish';
  public static readonly WORK_HALL_URL: string = 'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/formHome'
}