export class CommonUrls {
  public static readonly ZHLGD_URL: string = 'https://zhlgd.whut.edu.cn/tp_up/view';
  public static readonly WORK_HALL_REVIVE_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/taskcenter/tasktodoNew';
  public static readonly WORK_HALL_PROGRESS_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/myserviceapply/indexNew';
  public static readonly WORK_HALL_SCORE_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#from=formhome&act=fp/myserviceapply/indexFinish';
  public static readonly WORK_HALL_CLOSED_URL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/myserviceapply/indexFinish';
  public static readonly WORK_HALL_URL: string = 'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/formHome';
  public static readonly USER_LIBRARY: string =
    'https://zhlgd.whut.edu.cn/tp_up/view?m=up#act=up/sysintegration/userlibrary';
  public static readonly USER_EMAIL: string =
    'https://zhlgd.whut.edu.cn/tp_fp/view?m=fp#act=fp/serveapply&from=hall&serveID=7668c2e0-5a74-4d48-b8b9-1a9221943041';
  public static readonly USER_CARD: string = 'https://yktapp.whut.edu.cn/plat-pc/newsannouncement/main';
  public static readonly CAMPUS_NET_BASE: string = 'http://172.30.21.100'
}